vivpolls/urls.py
from django.conf.urls import url

from . import views

app_name = 'vivpolls'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

vpolls/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^vivpolls/', include('vivpolls.urls')),
    url(r'^admin/', admin.site.urls),
]

vivpolls/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'



class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

vivpolls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'vivpolls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'vivpolls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'vivpolls/results.html'


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'vivpolls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'vivpolls/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'vivpolls/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'vivpolls/detail.html',
                      {'question': question, 'error_message': "You didn't select a choice.", })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
    return HttpResponseRedirect(reverse('vivpolls:results', args=(question.id,)))

vivpolls/templates/vivpolls/detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'vivpolls/style.css' %}" />
<h1 style="text-align: center; color: darkgreen; padding-top: 50px">Cast your vote today!</h1>
<h1 style="text-align: left; padding-top: 150px; padding-left: 80px; padding-bottom: 30px; color: darkgreen">{{ question.question_text }}</h1>


{% if error_message %}<p style="text-align: left;padding-top: 100px"><strong>{{ error_message }}</strong></p>{% endif %}

<form style="text-align: left; padding-left: 100px" action="{% url 'vivpolls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br /><br />
{% endfor %}
<input style="margin-top: 20px; margin-left: 40px" type="submit" value="Vote" />
</form>

vivpolls/templates/vivpolls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'vivpolls/style.css' %}" />
<h1 style="text-align: center;padding-top: 50px;color: darkgreen">Welcome to the Poll of the day</h1>
<div style="text-align: left;padding-left: 100px;padding-top: 150px">
<h2>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li style="margin-bottom: 50px"><a href="{% url 'vivpolls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</h2>
</div>

vivpolls/templates/vivpolls/results.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'vivpolls/style.css' %}" />
<h1 style="text-align: center;color: darkgreen; padding-top: 50px"> Results thus far</h1>
<h1 style="text-align: left;padding-left: 150px; padding-top: 100px; color: darkgreen">{{ question.question_text }}</h1>

<ul style="padding-top: 50px; padding-left: 180px">
{% for choice in question.choice_set.all %}
    <li style="padding-bottom: 20px">{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a style="padding-left: 200px" href="{% url 'vivpolls:detail' question.id %}">Vote again?</a>